<?php

namespace Modules\HumanResource\Support;

class EmployeeReportLabels
{
    public static function columns(): array
    {
        return [
            'id' => 'លេខសម្គាល់កំណត់ត្រា', 'uuid' => 'លេខសម្គាល់តែមួយ', 'user_id' => 'លេខសម្គាល់គណនីអ្នកប្រើ',
            'employee_id' => 'លេខបុគ្គលិក', 'card_no' => 'លេខបណ្ណ', 'employee_code' => 'លេខកូដបុគ្គលិក',
            'official_id_10' => 'អត្តលេខមន្ត្រីរាជការ', 'first_name' => 'នាមខ្លួន', 'middle_name' => 'នាមកណ្ដាល', 'last_name' => 'នាមត្រកូល',
            'first_name_latin' => 'នាមខ្លួនជាអក្សរឡាតាំង', 'last_name_latin' => 'នាមត្រកូលជាអក្សរឡាតាំង',
            'full_name' => 'ឈ្មោះពេញ', 'full_name_latin' => 'ឈ្មោះពេញជាអក្សរឡាតាំង',
            'email' => 'អ៊ីមែល', 'phone' => 'លេខទូរសព្ទ', 'alternate_phone' => 'លេខទូរសព្ទបន្ថែម',
            'profile_image' => 'រូបថតបុគ្គលិក', 'employee_group_id' => 'លេខសម្គាល់ក្រុមបុគ្គលិក',
            'present_address' => 'អាសយដ្ឋានបច្ចុប្បន្ន', 'permanent_address' => 'អាសយដ្ឋានអចិន្ត្រៃយ៍',
            'degree_name' => 'ឈ្មោះសញ្ញាបត្រ', 'university_name' => 'ឈ្មោះគ្រឹះស្ថានសិក្សា', 'cgp' => 'និទ្ទេស ឬពិន្ទុមធ្យម', 'passing_year' => 'ឆ្នាំបញ្ចប់ការសិក្សា',
            'company_name' => 'ស្ថាប័នធ្លាប់បម្រើការងារ', 'working_period' => 'រយៈពេលបម្រើការងារ', 'duties' => 'ភារកិច្ច', 'supervisor' => 'អ្នកគ្រប់គ្រងផ្ទាល់',
            'signature' => 'ហត្ថលេខា', 'is_admin' => 'ជាអ្នកគ្រប់គ្រងប្រព័ន្ធ', 'maiden_name' => 'នាមមុនរៀបការ',
            'state_id' => 'លេខសម្គាល់រាជធានី ឬខេត្ត', 'city' => 'ក្រុង ឬស្រុក', 'zip' => 'លេខកូដប្រៃសណីយ៍', 'citizenship' => 'សញ្ជាតិ',
            'joining_date' => 'ថ្ងៃចូលបម្រើការងារ', 'hire_date' => 'ថ្ងៃជ្រើសរើសចូលធ្វើការ', 'promotion_date' => 'ថ្ងៃដំឡើងតួនាទី',
            'termination_date' => 'ថ្ងៃបញ្ចប់ការងារ', 'termination_reason' => 'មូលហេតុបញ្ចប់ការងារ',
            'national_id' => 'អត្តសញ្ញាណបណ្ណ', 'national_id_no' => 'លេខអត្តសញ្ញាណបណ្ណ', 'identification_attachment' => 'ឯកសារភ្ជាប់បញ្ជាក់អត្តសញ្ញាណ',
            'nationality' => 'សញ្ជាតិ', 'voluntary_termination' => 'ចាកចេញពីការងារដោយស្ម័គ្រចិត្ត', 'rehire_date' => 'ថ្ងៃចូលធ្វើការឡើងវិញ',
            'rate' => 'អត្រាប្រាក់ឈ្នួល', 'pay_frequency_id' => 'លេខសម្គាល់របៀបបើកប្រាក់', 'pay_frequency' => 'របៀបបើកប្រាក់', 'pay_frequency_text' => 'ការពិពណ៌នារបៀបបើកប្រាក់',
            'duty_type_id' => 'លេខសម្គាល់ប្រភេទភារកិច្ច', 'duty_type' => 'ប្រភេទភារកិច្ច', 'gender_id' => 'លេខសម្គាល់ភេទ', 'gender' => 'ភេទ',
            'marital_status_id' => 'លេខសម្គាល់ស្ថានភាពគ្រួសារ', 'marital_status' => 'ស្ថានភាពគ្រួសារ', 'attendance_time_id' => 'លេខសម្គាល់ម៉ោងវត្តមាន',
            'employee_type_id' => 'លេខសម្គាល់ប្រភេទបុគ្គលិក', 'employee_type' => 'ប្រភេទបុគ្គលិក',
            'contract_start_date' => 'ថ្ងៃចាប់ផ្ដើមកិច្ចសន្យា', 'contract_end_date' => 'ថ្ងៃផុតកំណត់កិច្ចសន្យា',
            'position_id' => 'លេខសម្គាល់មុខតំណែង', 'position' => 'មុខតំណែង', 'department_id' => 'លេខសម្គាល់អង្គភាពមេ', 'department' => 'អង្គភាពមេ',
            'sub_department_id' => 'លេខសម្គាល់អង្គភាពរង', 'sub_department' => 'អង្គភាពរង', 'branch_id' => 'លេខសម្គាល់សាខា',
            'is_full_right_officer' => 'ជាមន្ត្រីពេញសិទ្ធិ', 'service_start_date' => 'ថ្ងៃចូលក្របខណ្ឌរដ្ឋ', 'full_right_date' => 'ថ្ងៃតាំងស៊ប់',
            'legal_document_type' => 'ប្រភេទលិខិតគតិយុត្ត', 'legal_document_number' => 'លេខលិខិតគតិយុត្ត',
            'legal_document_date' => 'កាលបរិច្ឆេទលិខិតគតិយុត្ត', 'legal_document_subject' => 'កម្មវត្ថុលិខិតគតិយុត្ត',
            'legacy_pob_code' => 'លេខកូដទីកន្លែងកំណើតពីប្រព័ន្ធចាស់', 'legacy_pa_code' => 'លេខកូដអាសយដ្ឋានពីប្រព័ន្ធចាស់',
            'legacy_other_info' => 'ព័ត៌មានបន្ថែមពីប្រព័ន្ធចាស់', 'employee_device_id' => 'លេខបុគ្គលិកក្នុងម៉ាស៊ីនវត្តមាន',
            'highest_educational_qualification' => 'កម្រិតសិក្សាខ្ពស់បំផុត', 'national_education_level' => 'កម្រិតវប្បធម៌ទូទៅ',
            'hourly_rate' => 'ប្រាក់ឈ្នួលក្នុងមួយម៉ោង', 'hourly_rate2' => 'ប្រាក់ឈ្នួលក្នុងមួយម៉ោងបន្ថែម',
            'home_department' => 'អង្គភាពដើម', 'department_text' => 'ឈ្មោះអង្គភាពដែលបានកត់ត្រា',
            'class_code' => 'លេខកូដថ្នាក់', 'class_code_desc' => 'ការពិពណ៌នាថ្នាក់', 'class_acc_date' => 'ថ្ងៃទទួលថ្នាក់', 'class_status' => 'ស្ថានភាពថ្នាក់',
            'is_supervisor' => 'មានតួនាទីគ្រប់គ្រង', 'supervisor_id' => 'លេខសម្គាល់អ្នកគ្រប់គ្រងផ្ទាល់', 'supervisor_report' => 'ព័ត៌មានរាយការណ៍ទៅអ្នកគ្រប់គ្រង',
            'date_of_birth' => 'ថ្ងៃខែឆ្នាំកំណើត', 'birth_place_state_id' => 'លេខសម្គាល់រាជធានី ឬខេត្តកំណើត',
            'birth_place_city_id' => 'លេខសម្គាល់ក្រុង ឬស្រុកកំណើត', 'birth_place_commune_id' => 'លេខសម្គាល់ឃុំ ឬសង្កាត់កំណើត', 'birth_place_village_id' => 'លេខសម្គាល់ភូមិកំណើត',
            'ethnic_group' => 'ជនជាតិ', 'eeo_class_gp' => 'ក្រុមចំណាត់ថ្នាក់ឱកាសការងារ', 'ssn' => 'លេខសន្តិសុខសង្គម',
            'work_in_city' => 'ក្រុង ឬស្រុកបម្រើការងារ', 'live_in_state' => 'រាជធានី ឬខេត្តស្នាក់នៅ',
            'home_email' => 'អ៊ីមែលផ្ទាល់ខ្លួន', 'business_email' => 'អ៊ីមែលការងារ', 'home_phone' => 'ទូរសព្ទផ្ទះ', 'business_phone' => 'ទូរសព្ទការងារ', 'cell_phone' => 'ទូរសព្ទចល័ត',
            'emergency_contact_person' => 'ឈ្មោះអ្នកទំនាក់ទំនងពេលបន្ទាន់', 'emergency_contact_relationship' => 'អ្នកទំនាក់ទំនងបន្ទាន់ត្រូវជាអ្វីនឹងបុគ្គលិក',
            'emergency_contact' => 'លេខទូរសព្ទពេលបន្ទាន់', 'emergency_contact_country' => 'ប្រទេសអ្នកទំនាក់ទំនងពេលបន្ទាន់',
            'emergency_contact_state' => 'ខេត្តអ្នកទំនាក់ទំនងពេលបន្ទាន់', 'emergency_contact_city' => 'ក្រុង ឬស្រុកអ្នកទំនាក់ទំនងពេលបន្ទាន់',
            'emergency_contact_post_code' => 'លេខប្រៃសណីយ៍អ្នកទំនាក់ទំនងពេលបន្ទាន់', 'emergency_contact_address' => 'អាសយដ្ឋានអ្នកទំនាក់ទំនងពេលបន្ទាន់',
            'present_address_country' => 'ប្រទេសស្នាក់នៅបច្ចុប្បន្ន', 'present_address_state_id' => 'លេខសម្គាល់រាជធានី ឬខេត្តស្នាក់នៅបច្ចុប្បន្ន',
            'present_address_city_id' => 'លេខសម្គាល់ក្រុង ឬស្រុកស្នាក់នៅបច្ចុប្បន្ន', 'present_address_commune_id' => 'លេខសម្គាល់ឃុំ ឬសង្កាត់ស្នាក់នៅបច្ចុប្បន្ន',
            'present_address_village_id' => 'លេខសម្គាល់ភូមិស្នាក់នៅបច្ចុប្បន្ន', 'present_address_state' => 'ខេត្តស្នាក់នៅបច្ចុប្បន្ន',
            'present_address_city' => 'ក្រុង ឬស្រុកស្នាក់នៅបច្ចុប្បន្ន', 'present_address_post_code' => 'លេខប្រៃសណីយ៍បច្ចុប្បន្ន', 'present_address_address' => 'ទីលំនៅបច្ចុប្បន្នលម្អិត',
            'permanent_address_country' => 'ប្រទេសស្នាក់នៅអចិន្ត្រៃយ៍', 'permanent_address_state' => 'ខេត្តស្នាក់នៅអចិន្ត្រៃយ៍',
            'permanent_address_city' => 'ក្រុង ឬស្រុកស្នាក់នៅអចិន្ត្រៃយ៍', 'permanent_address_post_code' => 'លេខប្រៃសណីយ៍អចិន្ត្រៃយ៍', 'permanent_address_address' => 'ទីលំនៅអចិន្ត្រៃយ៍លម្អិត',
            'skill_type' => 'ប្រភេទជំនាញ', 'skill_name' => 'ឈ្មោះជំនាញ', 'certificate_type' => 'ប្រភេទវិញ្ញាបនបត្រ', 'certificate_name' => 'ឈ្មោះវិញ្ញាបនបត្រ', 'skill_attachment' => 'ឯកសារភ្ជាប់បញ្ជាក់ជំនាញ',
            'emergency_home_phone' => 'ទូរសព្ទផ្ទះសម្រាប់ពេលបន្ទាន់', 'emergency_work_phone' => 'ទូរសព្ទការងារសម្រាប់ពេលបន្ទាន់',
            'alter_emergency_contact' => 'អ្នកទំនាក់ទំនងបន្ទាន់បម្រុង', 'alter_emergency_home_phone' => 'ទូរសព្ទផ្ទះអ្នកទំនាក់ទំនងបម្រុង',
            'alter_emergency_work_phone' => 'ទូរសព្ទការងារអ្នកទំនាក់ទំនងបម្រុង', 'sos' => 'ព័ត៌មានជំនួយបន្ទាន់',
            'monthly_work_hours' => 'ចំនួនម៉ោងការងារប្រចាំខែ', 'employee_grade' => 'ឋានន្តរស័ក្តិ និងថ្នាក់', 'religion' => 'សាសនា',
            'no_of_kids' => 'ចំនួនកូន', 'spouse_count' => 'ចំនួនសហព័ទ្ធ', 'blood_group' => 'ក្រុមឈាម', 'health_condition' => 'ស្ថានភាពសុខភាព',
            'chronic_disease_history' => 'ប្រវត្តិជំងឺរ៉ាំរ៉ៃ', 'severe_disease_history' => 'ប្រវត្តិជំងឺធ្ងន់ធ្ងរ', 'surgery_history' => 'ប្រវត្តិវះកាត់',
            'regular_medication' => 'ថ្នាំដែលប្រើជាប្រចាំ', 'allergy_reaction' => 'ប្រតិកម្មអាលែកស៊ី',
            'vaccine_name' => 'ឈ្មោះវ៉ាក់សាំង', 'vaccine_protection' => 'ការការពាររបស់វ៉ាក់សាំង', 'vaccination_date' => 'ថ្ងៃចាក់វ៉ាក់សាំង', 'vaccination_place' => 'ទីកន្លែងចាក់វ៉ាក់សាំង',
            'covid_vaccine_dose' => 'ចំនួនដូសវ៉ាក់សាំងកូវីដ', 'covid_vaccine_name' => 'ឈ្មោះវ៉ាក់សាំងកូវីដ', 'covid_vaccine_date' => 'ថ្ងៃចាក់វ៉ាក់សាំងកូវីដ',
            'is_disable' => 'មានពិការភាព', 'disabilities_desc' => 'ព័ត៌មានលម្អិតអំពីពិការភាព',
            'uniform_shirt_size' => 'ទំហំអាវឯកសណ្ឋាន', 'uniform_pants_size' => 'ទំហំខោឯកសណ្ឋាន', 'uniform_shoe_size' => 'ទំហំស្បែកជើង',
            'profile_img_name' => 'ឈ្មោះឯកសាររូបថត', 'profile_img_location' => 'ទីតាំងឯកសាររូបថត',
            'iqama_no' => 'លេខបណ្ណស្នាក់នៅ', 'passport_no' => 'លេខលិខិតឆ្លងដែន', 'driving_license_no' => 'លេខបណ្ណបើកបរ', 'work_permit' => 'បណ្ណអនុញ្ញាតការងារ',
            'is_active' => 'ស្ថានភាពសកម្ម', 'is_left' => 'បានចាកចេញពីការងារ', 'work_status_id' => 'លេខសម្គាល់ស្ថានភាពការងារ',
            'work_status_name' => 'ស្ថានភាពការងារ', 'work_status' => 'ស្ថានភាពការងារ', 'service_state' => 'ស្ថានភាពបម្រើការងារ',
            'created_by' => 'អ្នកបញ្ចូលទិន្នន័យ', 'updated_by' => 'អ្នកកែប្រែទិន្នន័យ', 'created_at' => 'ថ្ងៃបញ្ចូលទិន្នន័យ',
            'updated_at' => 'ថ្ងៃកែប្រែចុងក្រោយ', 'deleted_at' => 'ថ្ងៃលុបទិន្នន័យ', 'default_shift_id' => 'លេខសម្គាល់វេនការងារគោល',
        ];
    }
}
