<?php

return [
    'module_key' => 'correspondence',
    'actions' => [
        'create_incoming' => 'Create incoming letter',
        'create_outgoing' => 'Create outgoing letter',
        'delegate' => 'Delegate',
        'office_comment' => 'Office comment',
        'deputy_review' => 'Deputy review',
        'director_decision' => 'Director decision',
        'distribute' => 'Distribute',
        'acknowledge' => 'Acknowledge',
        'feedback' => 'Feedback',
        'close' => 'Close case',
        'print' => 'Print',
    ],
    'templates' => [
        [
            'template_key' => 'administration_office_manager',
            'name' => 'Administration Office Correspondence Manager',
            'name_km' => 'ប្រធានការិយាល័យរដ្ឋបាល - លិខិត',
            'responsibility_key' => 'administration_office_manager',
            'default_scope_type' => 'self_and_children',
            'actions' => [
                'create_incoming',
                'create_outgoing',
                'office_comment',
                'distribute',
                'acknowledge',
                'feedback',
                'print',
            ],
            'conditions' => [
                'department_role' => 'administration_office',
            ],
            'reviewer_rules' => ['office_comment'],
            'approver_rules' => [],
            'commenter_rules' => ['office_comment', 'feedback'],
        ],
        [
            'template_key' => 'deputy_reviewer',
            'name' => 'Correspondence Deputy Reviewer',
            'name_km' => 'អនុប្រធានពិនិត្យលិខិត',
            'responsibility_key' => 'deputy_reviewer',
            'default_scope_type' => 'self_and_children',
            'actions' => ['delegate', 'deputy_review', 'distribute', 'close', 'print'],
            'conditions' => [],
            'reviewer_rules' => ['deputy_review'],
            'approver_rules' => [],
            'commenter_rules' => ['feedback'],
        ],
        [
            'template_key' => 'director_final_approver',
            'name' => 'Correspondence Director Final Approver',
            'name_km' => 'ប្រធានអនុម័តចុងក្រោយលិខិត',
            'responsibility_key' => 'director_final_approver',
            'default_scope_type' => 'self_and_children',
            'actions' => ['director_decision', 'delegate', 'distribute', 'close', 'print'],
            'conditions' => [],
            'reviewer_rules' => [],
            'approver_rules' => ['director_decision'],
            'commenter_rules' => [],
        ],
    ],
    'workflow_policies' => [
        [
            'policy_key' => 'incoming_letter_default',
            'request_type_key' => 'incoming_letter',
            'name' => 'Incoming letter workflow',
            'conditions' => [],
            'steps' => [
                ['step_key' => 'office_comment', 'actor_template_key' => 'administration_office_manager', 'action_type' => 'review'],
                ['step_key' => 'deputy_review', 'actor_template_key' => 'deputy_reviewer', 'action_type' => 'recommend'],
                ['step_key' => 'director_decision', 'actor_template_key' => 'director_final_approver', 'action_type' => 'approve'],
            ],
        ],
        [
            'policy_key' => 'outgoing_letter_default',
            'request_type_key' => 'outgoing_letter',
            'name' => 'Outgoing letter workflow',
            'conditions' => [],
            'steps' => [
                ['step_key' => 'outgoing_review', 'actor_template_key' => 'administration_office_manager', 'action_type' => 'review'],
                ['step_key' => 'outgoing_approval', 'actor_template_key' => 'director_final_approver', 'action_type' => 'approve'],
            ],
        ],
    ],
];
